Correction of installing from user
radareorg/radare2-pm pull request #138
Opened 2022-05-25 13:40 UTC by fr0ster

**Checklist**

- [ ] Closing issues: #issue
- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

Add print info message and deletion of before new installing

2022-05-26 13:21 UTC, trufae commented on db/r2ghidra-sleigh
> +			echo "Moving r2ghidra_sleigh in $(r2 -HR2_LIBR_PLUGINS)"
Make this conditional above and just mkdir the system path instead of doing all the work on someone's user and then moving it to system

2022-05-27 07:47 UTC, closed without merging

2022-05-27 07:51 UTC, trufae requested changes

2022-05-27 07:51 UTC, trufae commented on db/r2ghidra-sleigh
> +        ./configure --prefix=`r2 -H R2_PREFIX`
also || return 1

2022-05-27 07:51 UTC, trufae commented on db/r2ghidra-sleigh
> +            ${SUDO} ${MAKE} -C ghidra install
|| return 1

2022-05-27 08:05 UTC, fr0ster commented on db/r2ghidra-sleigh
> +		local _sudo
For local installing needs have empty SUDO variable in this case

2022-05-27 08:18 UTC, fr0ster commented on db/r2ghidra-sleigh
> +        if [ "${GLOBAL}" = 1 ]; then
It is in USE_BIN block, isn't it?

2022-05-27 08:18 UTC, fr0ster commented on db/r2ghidra-sleigh
> +        ./configure --prefix=`r2 -H R2_PREFIX`
Added